### ISSUE TITLE
command 'extension.openRecentFiles' not found

### ISSUE THREAD

**Issue by abigwonderful** [wahyd4/vscode-plugin-recent-files#1]
Howdy - I'm relatively new to VS Code and was psyched to find your extension. Have you encountered this error after installing:
`command 'extension.openRecentFiles' not found`

**Comment by wahyd4** [comment]
Yeah, It occurred sometimes. But I don't have any thoughts about how this happened.  

 I will try to fix it later. If you have any ideas, that would be great. 

I registered to activate this plugin by `*`, which means it will initialize whenever VScode starts up.  
You can see something at package.json/
``` json
"activationEvents": [
        "*"
  ]
```

**Comment by wahyd4** [comment]
@abigwonderful  Just released a minor version with 1.0.4. 
You can try to update your VS code and see if this issue has been fixed.

**Comment by abigwonderful** [comment]
@wahyd4 Success thanks for jumping on that!

**Comment by wahyd4** [comment]
@abigwonderful The previous version still has the issue that when you start vscode without open any files. You can update to the latest version and giva a try.
Thanks.
