### ISSUE TITLE
Ctrl-N Ctrl-P (cmd-n, cmd-p) support for navigating files

### ISSUE THREAD

**Issue by lawreenas** [wahyd4/vscode-plugin-recent-files#4]
Hi,
Ctrl-n ctrl-p is a common way to navigate to next or previous lines. I think your plugin should also leverage this.

**Comment by wahyd4** [comment]
Hi @lawreenas, why don't you just use the ↑ and ↓ keys to navigate files in the recently opened file list? This only needs press one key.

**Comment by lawreenas** [comment]
Hi @wahyd4, yes I can, but it's not as comfortable as using `cmd + n` `cmd + p`. It's a common keybinding in all lists, that more advanced users use., for fast navigation - since you keep your index finders on `f` and `j` keys. Less hand movement.

**Comment by wahyd4** [comment]
OK, I got it.  I double checked that all the list in vs code does support `cmd + n` `cmd + p` to navigate. But on my Mac which is `ctrl+n` and `ctrl+p`,  the `cmd+n` will always open a new tab.

Anyway, I will find some time and try to implement this feature. If you could implement this and made a pull request that would be great!

**Comment by lawreenas** [comment]
I'm sorry, you're right - it's `ctrl + n/p` in both mac and pc.
If I'll have some time off, I could try doing it, but I've 0 experience in `vscode` plugin development, so I would not count on me too much..

**Comment by wahyd4** [comment]
Hi @lawreenas， Please update the plugin to the latest version. Which has solved this issue.
I just add two more key binding in my plugin.
```json
          {
                "key": "ctrl+n",
                "command": "workbench.action.quickOpenSelectNext",
                "when": "!editorFocus"
            },
            {
                "key": "ctrl+p",
                "command": "workbench.action.quickOpenSelectPrevious",
                "when": "!editorFocus"
            }
```
Which means you can use `ctrl + n` and `ctrl + p` to do file naviagation among all plugins who used quick open list api.

**Comment by wahyd4** [comment]
So, I will close this issue now.
