### ISSUE TITLE
Support for multi-folder workspaces

### ISSUE THREAD

**Issue by mostr** [wahyd4/vscode-plugin-recent-files#6]
New VSCode Insiders adds ability to have multi-project workspaces. Looks like the extension doesn't work well with that, as it only shows recent files from one (first on the explorer's list) project.

**Comment by wahyd4** [comment]
@mostr , sorry for the late response.
I'm will not implement this feature, due to the VSCode `Go to file` command just have this extension's functionality. 

Just open your keybindings.json and add the following in OSX:
```json
{
    "key": "cmd+e", 
    "command": "workbench.action.quickOpen"
  }
```
or this in Windows
```json
{
    "key": "ctrl+e", 
    "command": "workbench.action.quickOpen"
  },
```

**Comment by mostr** [comment]
Yeah but it not really does exactly the same as far as I can see :(
Anyway, thanks for letting me know on that.

**Comment by wahyd4** [comment]
The `Go to file` command popup list the files you recently opened in a reverse order by default.
It's the same logic with Intellij's
