### ISSUE TITLE
command '-actions.find' not found

### ISSUE THREAD

**Issue by rikvanderkemp** [wahyd4/vscode-plugin-recent-files#8]
Just installed this extension but I get the message 

```
command '-actions.find' not found
```

Visual Code 1.20 on Linux

**Comment by wahyd4** [comment]
Hi, this plugin only registered with one command which is `extension.openRecentFiles`, and no such `find` commands.

Please check other plugins you installed.

**Comment by rikvanderkemp** [comment]
Well apparently something registered this keybinding. thanks, closing issue
