### ISSUE TITLE
Make the not maintainability notice visible in the plugin info

### ISSUE THREAD

**Issue by andybergon** [wahyd4/vscode-plugin-recent-files#9]
![image](https://user-images.githubusercontent.com/5220825/38462815-a8da650e-3ae4-11e8-807a-6ecff9951a49.png)

This is what you see when you search for the plugin inside vscode. Can you upgrade the info to reflect the README and say that you will no more update the extension and to use the built in functionality.

**Comment by wahyd4** [comment]
Thanks, I will try to update the readme in vscode market.

**Comment by wahyd4** [comment]
Updated

**Comment by andybergon** [comment]
vscode extension noob here. Do you need to manually `vsce publish` or will it be picked up eventually from the marketplace?

**Comment by wahyd4** [comment]
You need to do `vsce publish` manually to update the  readme
